"""
BERT WordPiece tokenizer (uncased), pure Python, for serving the distilled guard without the `tokenizers` package.

Why not `tokenizers`: it depends on huggingface-hub and, through it, a dozen more packages, to do something that is a page of code. This repository hash-locks every dependency and keeps the 512 MB
image small, so the runtime dependencies of the student layer are `onnxruntime` and numpy and nothing else.

The algorithm is BERT's (BasicTokenizer + WordpieceTokenizer, uncased, tokenize_chinese_chars=True), as implemented by the Hugging Face FAST (Rust) tokenizer, which is what the student was trained with:
  1. clean: drop NUL, U+FFFD and the control categories Cc, Cf, Co, Cs (unassigned code points are KEPT, each becoming an [UNK] word); every other whitespace character becomes a space;
  2. put spaces around CJK ideographs (the fast tokenizer's ranges, which leave out U+2B820-2B91F);
  3. split on whitespace; lower-case each token, strip accents (NFD, drop combining marks) and split it on punctuation;
  4. WordPiece, greedy longest match first, continuation pieces prefixed `##`; a word longer than 100 characters, or one with no valid segmentation, is a single [UNK];
  5. [CLS] ... [SEP], truncated so the whole sequence is at most `max_length`.

The fast tokenizer is NOT the same as BERT's original Python tokenizer (which drops every C* category), and its Unicode tables are older than Python 3.12's, which is why a few hundred
code points need the override table below. Serving has to match training, so the reference here is the fast tokenizer, and the evidence is exhaustive: scripts/wordpiece_fuzz.py compares
every Unicode code point, alone, between letters and after a letter, and reports zero differences under Python 3.12 (Unicode 15.0); tests/test_wordpiece.py replays 473 reference-encoded texts in CI.
The fuzz must be re-run, and the table regenerated (`--emit`), if the Python or tokenizers version changes.

One deliberate difference from the Hugging Face fast tokenizer: text that happens to read `[SEP]`, `[CLS]`, `[MASK]` is NOT turned into the special token (the fast tokenizer does that by default,
which lets a prompt smuggle structural tokens into the model's input); here it is tokenized as the plain characters it is. Everywhere else the ids are identical.
"""
import json
import unicodedata
from bisect import bisect_right
from pathlib import Path

MAX_WORD_CHARS = 100

# Code points the tokenizer's own (older) Unicode tables do not classify, so it treats them as ordinary characters: not control, not punctuation, not a combining mark. They are newer than
# its tables (combining marks, punctuation, symbols and format characters assigned in Unicode 11-15), and this interpreter's `unicodedata` (Python 3.12: Unicode 15.0) does know them.
# Generated by scripts/wordpiece_fuzz.py --emit, which compares every code point with the fast tokenizer; regenerate it if the Python or tokenizers version changes.
_UNKNOWN_TO_TOKENIZER = (
    (0x61D, 0x61D), (0x7FD, 0x7FD), (0x890, 0x891), (0x898, 0x89F), (0x8CA, 0x8E2), (0x9FD, 0x9FE), (0xA76, 0xA76), (0xAFA, 0xAFF), (0xB55, 0xB55),
    (0xC04, 0xC04), (0xC3C, 0xC3C), (0xC77, 0xC77), (0xC84, 0xC84), (0xD00, 0xD00), (0xD3B, 0xD3C), (0xD81, 0xD81), (0xEBA, 0xEBA), (0xECE, 0xECE),
    (0x166D, 0x166D), (0x1734, 0x1734), (0x180F, 0x180F), (0x1885, 0x1886), (0x1ABF, 0x1ACE), (0x1B7D, 0x1B7E), (0x1DF6, 0x1DFB), (0x2E43, 0x2E4F),
    (0x2E52, 0x2E5D), (0xA82C, 0xA82C), (0xA8C5, 0xA8C5), (0xA8FF, 0xA8FF), (0xA9BD, 0xA9BD), (0x10D24, 0x10D27), (0x10EAB, 0x10EAD), (0x10EFD,
    0x10EFF), (0x10F46, 0x10F50), (0x10F55, 0x10F59), (0x10F82, 0x10F89), (0x11070, 0x11070), (0x11073, 0x11074), (0x110C2, 0x110C2), (0x110CD,
    0x110CD), (0x111C9, 0x111C9), (0x111CF, 0x111CF), (0x1123E, 0x1123E), (0x11241, 0x11241), (0x1133B, 0x1133B), (0x11438, 0x1143F), (0x11442,
    0x11444), (0x11446, 0x11446), (0x1144B, 0x1144F), (0x1145A, 0x1145B), (0x1145D, 0x1145E), (0x11660, 0x1166C), (0x116B9, 0x116B9), (0x1182F,
    0x11837), (0x11839, 0x1183B), (0x1193B, 0x1193C), (0x1193E, 0x1193E), (0x11943, 0x11946), (0x119D4, 0x119D7), (0x119DA, 0x119DB), (0x119E0,
    0x119E0), (0x119E2, 0x119E2), (0x11A01, 0x11A0A), (0x11A33, 0x11A38), (0x11A3B, 0x11A47), (0x11A51, 0x11A56), (0x11A59, 0x11A5B), (0x11A8A,
    0x11A96), (0x11A98, 0x11A9C), (0x11A9E, 0x11AA2), (0x11B00, 0x11B09), (0x11C30, 0x11C36), (0x11C38, 0x11C3D), (0x11C3F, 0x11C3F), (0x11C41,
    0x11C45), (0x11C70, 0x11C71), (0x11C92, 0x11CA7), (0x11CAA, 0x11CB0), (0x11CB2, 0x11CB3), (0x11CB5, 0x11CB6), (0x11D31, 0x11D36), (0x11D3A,
    0x11D3A), (0x11D3C, 0x11D3D), (0x11D3F, 0x11D45), (0x11D47, 0x11D47), (0x11D90, 0x11D91), (0x11D95, 0x11D95), (0x11D97, 0x11D97), (0x11EF3,
    0x11EF4), (0x11EF7, 0x11EF8), (0x11F00, 0x11F01), (0x11F36, 0x11F3A), (0x11F40, 0x11F40), (0x11F42, 0x11F4F), (0x11FFF, 0x11FFF), (0x12FF1,
    0x12FF2), (0x13430, 0x13440), (0x13447, 0x13455), (0x16E97, 0x16E9A), (0x16F4F, 0x16F4F), (0x16FE2, 0x16FE2), (0x16FE4, 0x16FE4), (0x1CF00,
    0x1CF2D), (0x1CF30, 0x1CF46), (0x1E000, 0x1E006), (0x1E008, 0x1E018), (0x1E01B, 0x1E021), (0x1E023, 0x1E024), (0x1E026, 0x1E02A), (0x1E08F,
    0x1E08F), (0x1E130, 0x1E136), (0x1E2AE, 0x1E2AE), (0x1E2EC, 0x1E2EF), (0x1E4EC, 0x1E4EF), (0x1E944, 0x1E94A), (0x1E95E, 0x1E95F)
)
_UNKNOWN_STARTS = tuple(a for a, _ in _UNKNOWN_TO_TOKENIZER)
# Three code points whose category CHANGED between the tokenizer's Unicode tables and Unicode 15 (not new assignments): it strips U+1734 as a combining mark and splits on
# U+111C9 and U+166D as punctuation.
_TOKENIZER_MARKS = frozenset({0x1734})
_TOKENIZER_PUNCTUATION = frozenset({0x111C9, 0x166D})


def _unknown_to_tokenizer(ch: str) -> bool:
    cp = ord(ch)
    i = bisect_right(_UNKNOWN_STARTS, cp) - 1
    return i >= 0 and cp <= _UNKNOWN_TO_TOKENIZER[i][1]


def _is_whitespace(ch: str) -> bool:
    return ch in " \t\n\r" or unicodedata.category(ch) == "Zs"


def _is_control(ch: str) -> bool:
    # The Hugging Face fast tokenizer the model was trained with drops categories Cc, Cf, Co and Cs but KEEPS unassigned code points (Cn), each of which then becomes an [UNK] word of its own.
    # BERT's original Python tokenizer drops every C* category including Cn. Serving must match training, so this follows the fast one (found by scripts/wordpiece_fuzz.py).
    if ch in "\t\n\r":
        return False
    category = unicodedata.category(ch)
    return category.startswith("C") and category != "Cn" and not (category == "Cf" and _unknown_to_tokenizer(ch))


def _is_punctuation(ch: str) -> bool:
    cp = ord(ch)
    if 33 <= cp <= 47 or 58 <= cp <= 64 or 91 <= cp <= 96 or 123 <= cp <= 126:
        return True
    return cp in _TOKENIZER_PUNCTUATION or (unicodedata.category(ch).startswith("P") and not _unknown_to_tokenizer(ch))


def _is_cjk(cp: int) -> bool:
    return (0x4E00 <= cp <= 0x9FFF or 0x3400 <= cp <= 0x4DBF or 0x20000 <= cp <= 0x2A6DF or 0x2A700 <= cp <= 0x2B73F or 0x2B740 <= cp <= 0x2B81F
            or 0x2B920 <= cp <= 0x2CEAF or 0xF900 <= cp <= 0xFAFF or 0x2F800 <= cp <= 0x2FA1F)      # the fast tokenizer's ranges: U+2B820-2B91F are not in it


def _clean(text: str) -> str:
    out = []
    for ch in text:
        cp = ord(ch)
        if cp == 0 or cp == 0xFFFD or _is_control(ch):
            continue
        out.append(" " if _is_whitespace(ch) else ch)
    return "".join(out)


def _space_cjk(text: str) -> str:
    out = []
    for ch in text:
        if _is_cjk(ord(ch)):
            out.extend((" ", ch, " "))
        else:
            out.append(ch)
    return "".join(out)


def _strip_accents(token: str) -> str:
    return "".join(ch for ch in unicodedata.normalize("NFD", token)
                   if (unicodedata.category(ch) != "Mn" or _unknown_to_tokenizer(ch)) and ord(ch) not in _TOKENIZER_MARKS)


def _split_punctuation(token: str) -> list[str]:
    pieces, current = [], []
    for ch in token:
        if _is_punctuation(ch):
            if current:
                pieces.append("".join(current))
                current = []
            pieces.append(ch)
        else:
            current.append(ch)
    if current:
        pieces.append("".join(current))
    return pieces


class WordPieceTokenizer:
    def __init__(self, vocab: dict[str, int]):
        self.vocab = vocab
        self.unk, self.cls, self.sep = vocab["[UNK]"], vocab["[CLS]"], vocab["[SEP]"]

    @classmethod
    def from_file(cls, path: Path) -> "WordPieceTokenizer":
        tokens = Path(path).read_text(encoding="utf-8").split("\n")
        if tokens and tokens[-1] == "":
            tokens.pop()
        return cls({tok: i for i, tok in enumerate(tokens)})

    @classmethod
    def from_tokenizer_json(cls, path: Path) -> "WordPieceTokenizer":
        """Load the WordPiece vocabulary from a Hugging Face tokenizer.json."""
        tokenizer = json.loads(Path(path).read_text(encoding="utf-8"))
        model = tokenizer.get("model")
        if not isinstance(model, dict) or model.get("type") != "WordPiece":
            raise ValueError(f"{path} does not contain a WordPiece tokenizer")
        normalizer = tokenizer.get("normalizer")
        if not isinstance(normalizer, dict) or normalizer.get("type") != "BertNormalizer":
            raise ValueError(f"{path} does not use the supported BERT normalizer")
        if not (
            normalizer.get("clean_text") is True
            and normalizer.get("handle_chinese_chars") is True
            and normalizer.get("lowercase") is True
            and (normalizer.get("strip_accents") is None or normalizer.get("strip_accents") is True)
        ):
            raise ValueError(f"{path} has unsupported BERT normalizer settings")
        pre_tokenizer = tokenizer.get("pre_tokenizer")
        if not isinstance(pre_tokenizer, dict) or pre_tokenizer.get("type") != "BertPreTokenizer":
            raise ValueError(f"{path} does not use the supported BERT pre-tokenizer")
        if model.get("continuing_subword_prefix") != "##" or model.get("unk_token") != "[UNK]":
            raise ValueError(f"{path} has unsupported WordPiece settings")
        if model.get("max_input_chars_per_word", MAX_WORD_CHARS) != MAX_WORD_CHARS:
            raise ValueError(f"{path} has unsupported WordPiece maximum word length")
        vocab = model.get("vocab")
        if not isinstance(vocab, dict) or not vocab or any(
            not isinstance(token, str) or not isinstance(token_id, int) or isinstance(token_id, bool)
            for token, token_id in vocab.items()
        ):
            raise ValueError(f"{path} has an invalid WordPiece vocabulary")
        ids = set(vocab.values())
        if ids != set(range(len(vocab))):
            raise ValueError(f"{path} WordPiece vocabulary IDs must be contiguous from zero")
        required = {"[UNK]", "[CLS]", "[SEP]"}
        if not required.issubset(vocab):
            raise ValueError(f"{path} WordPiece vocabulary is missing {sorted(required - set(vocab))}")
        return cls(vocab)

    def _wordpiece(self, word: str) -> list[int]:
        if len(word) > MAX_WORD_CHARS:
            return [self.unk]
        ids, start = [], 0
        while start < len(word):
            end, found = len(word), None
            while start < end:
                piece = word[start:end]
                if start > 0:
                    piece = "##" + piece
                if piece in self.vocab:
                    found = self.vocab[piece]
                    break
                end -= 1
            if found is None:
                return [self.unk]
            ids.append(found)
            start = end
        return ids

    def tokenize(self, text: str) -> list[int]:
        ids: list[int] = []
        for word in _space_cjk(_clean(text)).split():
            for piece in _split_punctuation(_strip_accents(word.lower())):
                ids.extend(self._wordpiece(piece))
        return ids

    def encode(self, text: str, max_length: int = 256) -> list[int]:
        room = max_length - 2
        ids: list[int] = []
        for word in _space_cjk(_clean(text)).split():
            for piece in _split_punctuation(_strip_accents(word.lower())):
                ids.extend(self._wordpiece(piece))
            if len(ids) >= room:                       # the rest of a long input would be cut off anyway
                break
        return [self.cls, *ids[:room], self.sep]
